# Generated by Django 3.1 on 2022-06-15 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='dispatch_4',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='dispatch_4'),
        ),
        migrations.AddField(
            model_name='device',
            name='dispatch_5',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='dispatch_5'),
        ),
        migrations.AddField(
            model_name='device',
            name='dispatch_6',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='dispatch_6'),
        ),
        migrations.AddField(
            model_name='device',
            name='dispatch_7',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='dispatch_7'),
        ),
        migrations.AddField(
            model_name='device',
            name='dispatch_8',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='dispatch_8'),
        ),
    ]
