# Generated by Django 3.1 on 2022-06-17 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_dispatchlist_error_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchlist',
            name='publish_count',
            field=models.IntegerField(default=0, verbose_name='推播警戒值'),
        ),
        migrations.AddField(
            model_name='dispatchlist',
            name='publish_status',
            field=models.IntegerField(default=0, verbose_name='推播狀態'),
        ),
    ]
