version: "3"

networks:
  elastic_stack:
    driver: bridge

services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.3
    environment:
      - "discovery.type=single-node"
      # - "ES_JAVA_OPTS=-Xms$ES_MEM -Xmx"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    networks:
      - elastic_stack
    ports:
      - 0.0.0.0:9200:9200
      - 0.0.0.0:9300:9300

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.16.3
    environment:
      - ELSTICSEARCH_HOSTS=localhost:9200
    networks:
      - elastic_stack
    ports:
      - 0.0.0.0:5601:5601
    depends_on:
      - elasticsearch

  filebeat:
    container_name: filebeat
    image: docker.elastic.co/beats/filebeat:7.16.3
    networks:
      - elastic_stack
    user: root
    environment:
      - setup.kibana.host=kibana:5601
      - output.elasticsearch.hosts=["elasticsearch:9200"]
      - -strict.perms=false
    command: --strict.perms=false -e
    volumes:
      - "../filebeat.yml:/usr/share/filebeat/filebeat.yml:ro"
      - ../log:/var/log
      - /var/lib/docker/containers:/var/lib/docker/containers
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - kibana

  logstash:
    container_name: logstash
    image: docker.elastic.co/logstash/logstash:7.16.3
    volumes:
      - ../pipeline/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:rw
    networks:
      - elastic_stack
    ports:
      - 0.0.0.0:5044:5044
      - 0.0.0.0:9600:9600
    depends_on:
      - filebeat
